### ISSUE TITLE
Update version of Rails, Ruby and libraries

### ISSUE THREAD

**Issue by bendycode** [bendyworks/payroll#198]
Break this into separate stories in whatever manner makes this work more manageable and approachable.

**Comment by aterrype** [comment]
Did you mean any specific libraries, or did you just mean in general? There's an open PR for updating Ruby and anything that was dependent on that, and dependabot keeps Rails and a lot of the libraries up-to-date, but I want to make sure you didn't mean anything more specific that wouldn't get fixed by that before I mark this as fixed by the open PR.

**Comment by bendycode** [comment]
I just meant in general. 

Thanks!
