### ISSUE TITLE
Add a javascript formatter

### ISSUE THREAD

**Issue by Code47X** [bendyworks/payroll#262]
I'd like to add a JavaScript formatter config to this project to keep the codebase clean! I personally really like prettier, with this config:

```
{
  "printWidth": 120,
  "singleQuote": true,
  "semi": true,
  "tabWidth": 2,
  "trailingComma": "es5"
}
```
Thoughts?

**Comment by aterrype** [comment]
I think that's a good idea - we presumably haven't done it because this project has so little JS, but if we're adding webpacker that will probably change. printWidth should probably be 100 for consistency with rubocop, but other than that I feel like having a consistent standard is more important than what the standard is, so those options look fine.

**Comment by Code47X** [comment]
Added in #261 along with eslint. We can add linting/formatting to the CI pipeline if needed.
