### ISSUE TITLE
Proposed dates in the planning tab are lost on refresh

### ISSUE THREAD

**Issue by aterrype** [bendyworks/payroll#58]
In the planning tab, if you enter a proposed date, tab away, and refresh, the date is lost. The behavior is the same regardless of whether the date is entered manually or through the dropdown calendar. This doesn't happen with the other two proposal fields (though the proposed raise field has a similar issue, which might be related.) The date should be saved like the other information.

Edit: the problem is that dates are being entered in mdy format, but saved in dmy format. So dates are lost entirely if the date is after the 12th of the month, and saved as the wrong date otherwise.

**Comment by aterrype** [comment]
@bendycode It's not clear what the desired behavior of this field is. Which date format should the proposed date field show? Right now you can enter either month/day/year or year-month-day, but month/day/year causes this bug and year-month-day works but with minor visual issues (slashes don't appear until you refresh). Year-month-day is the current display, but month/day/year would be consistent with the start date field.

**Comment by bendycode** [comment]
@aterrype: Nice catch!  let's go with month/day/year format, since that's natural for us in the US.  It's possible I might have caused this in the past by wanting just to say which month, without specifying a date. Such a desire no longer applies though, as it turns out we should propose a specific day every time for clarity and specificity.
Thanks!

**Comment by wubr** [comment]
`best_in_place` creates this field as a jQuery date picker when we use `as: :date`.

https://api.jqueryui.com/datepicker/
> Creating a datepicker on an <input type="date"> is not supported due to a UI conflict with the native picker. 

We end up with an input of type `text` which BIP doesn't allow us to override, and when it submits this data it does it in whatever format it's been entered in.  It could be typed manually in some format, or it could be the format set as the default through the datepicker's api if the user has selected a date through the picker.  This differs from the non-BIP date fields which can use input type `date`, the browser built-in picker, and submits using ISO8601 yyyy-mm-dd.  

So instead of getting the expected ISO8601 version, rails could get a number of formats, which it might have trouble parsing without help - the US mm/dd/yyyy doesn't `Date.parse`, so it seems like in order to accept US dates we need to intercept the parameters on the backend and possibly reformat this date value so ActiveRecord can parse and persist it correctly.

I briefly tried removing the `as: :date`, replacing it with `html_attrs: { type: 'date' }`.  That does override the form input field when BIP activates the form, but other code in BIP is assuming it is going to be a `text` type and does jquery with those assumptions, so the override breaks functionality.
